name: Terraform

on:
  push:
    branches:
      - main

jobs:
  provision-resources:
    name: Provision Resources
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@latest

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@latest
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}