name: Terraform Apply
on:
  push:
    branches:
      - main
jobs:
  apply:
    name: Apply
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Check Out
        uses: actions/checkout@v3.0.2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          aws-region: us-east-1
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      - name: Prepare Lambda
        run: |
          cd ../lambda
          for dir in */; do
            cd $dir
            if test -f requirements.txt; then
              pip install --target package $(<requirements.txt)
              cd package
              zip -r ../package .
              cd ..
            fi
            zip -g package *
            cd ..
          done
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan
      - name: Terraform Apply
        run: terraform apply --auto-approve
